emberjs/ember-rails

test/dummy/config/initializers/workaround_for_ams.rb
This workaround is no longer needed in 0.9.3.
=> Remove workaround for ActiveModelSerializers gem

README.md
Now I think almost of Ember Rails users knows about component very well.
=> Remove obsolete section in README

ember-rails.gemspec, test/precompile_test.rb
It throws the following error:
```
ReferenceError: Can't find variable: window
```
This commit fixes https://github.com/emberjs/ember-rails/issues/442 .
=> Don't use handlebars-source 3

lib/ember/handlebars/template.rb, test/hjstemplate_test.rb
When `amd_namespace` is `nil` , AMD module name is beginning with `/`.
Otherwise, Ember don't expect this format.
=> Remove heading `/` of AMD template target

lib/ember_rails.rb
The bundled assets (like a `ember-runtime.js` or `ember-template-compiler.js` etc) may be needed from some projects without handlebars precompilation.
To reference these files, bundles assets should be on asset paths.
=> Setup bundled assets in ember-source & ember-data-source

ember-rails.gemspec, lib/ember_rails.rb, test/dummy/config/application.rb, test/test_helper.rb
**Please do not merge this**
The following features became optional.
* handlebars precompilation
* Appending handlebars to sprockets path
=> Remove handlebars dependency

ember-rails.gemspec
Only barber depend on execjs.
This version restriction should be specified from barber.
ref: https://github.com/tchak/barber/commit/071487d6c1fdf35deae19117bd2041fad1cf211b
=> Remove execjs dependency

lib/generators/ember/controller_generator.rb, lib/generators/ember/resource_generator.rb, lib/generators/templates/object_controller.js, lib/generators/templates/object_controller.js.coffee, lib/generators/templates/object_controller.js.em
`Ember.ObjectController` is deprecated since Ember.js 1.10.0.
=> Update generator using `Ember.Controller` instead of `Ember.ObjectController`

lib/generators/ember/install_generator.rb
Remove the fallback to beta channel since ember data has now an official release channel.
I'm not familiar with VCR, so i removed the corresponding cassette and let the test rebuild it. Let me know if there was a prefferred way to do it.
=> use the ember data release channel

.travis.yml, Appraisals, ember-rails.gemspec, gemfiles/rails32_ember_18.gemfile, gemfiles/rails32_ember_latest.gemfile, gemfiles/rails41_ember_18.gemfile, gemfiles/rails41_ember_latest.gemfile, gemfiles/rails42_ember_18.gemfile, gemfiles/rails42_ember_latest.gemfile, gemfiles/rails4_ember_18.gemfile, gemfiles/rails4_ember_latest.gemfile, gemfiles/sprockets_3.gemfile
We want to follow Ember Data's released version.
This is an advance preparation of https://github.com/emberjs/ember-rails/pull/478.
=> Drop old ember

lib/ember/rails/engine.rb
This is the same fix as https://github.com/emberjs/ember-rails/pull/489 for old ember-source supported version.
=> Use `Ember::Handlebars::Template.setup`

lib/generators/ember/install_generator.rb
Use the 'prod' variant when downloading ember from the CDN for production version, I'd hope everyone is handling minification themselves
=> Use the 'prod' variant when downloading ember

Appraisals, gemfiles/sprockets_rails_3.gemfile
sprockets-rails 3.0.0 is released now.
https://github.com/rails/sprockets-rails/tree/v3.0.0
=> Update sprockets-rails version to 3.0.0 for test

lib/generators/templates/environment.coffee, lib/generators/templates/environment.em
There is a typo in environment.coffee and environment.em files when using generators.
=> Fix environment.coffee/em generator typo

lib/ember_rails.rb, test/dummy/app/assets/javascripts/transforms/user.module.es6, test/es6_modeul_test.rb, test/es6_module_test.rb
allow models to have custom DS.attr transforms
=> include ember-data custom transforms in namespace

lib/generators/templates/application.coffee, lib/generators/templates/application.em, test/generators/bootstrap_generator_test.rb
Fix https://github.com/emberjs/ember-rails/issues/512
=> Fix to generated app file path for coffee & em

lib/generators/ember/bootstrap_generator.rb, test/generators/bootstrap_generator_test.rb
To follow updating `ember.prefix_dirs` in automatically.
=> Generate bootstrap with `ember.prefix_dirs`

.travis.yml, test/hjstemplate_test.rb, test/precompile_test.rb
Ember.js 2.10 has some internal changes.
This PR fixes failing tests depending internal API.
=> Fix tests for latest ember

lib/generators/ember/adapter_generator.rb, lib/generators/ember/bootstrap_generator.rb, lib/generators/ember/component_generator.rb, lib/generators/ember/controller_generator.rb, lib/generators/ember/initializer_generator.rb, lib/generators/ember/instance_initializer_generator.rb, lib/generators/ember/model_generator.rb, lib/generators/ember/resource_generator.rb, lib/generators/ember/resource_override.rb, lib/generators/ember/route_generator.rb, lib/generators/ember/service_generator.rb, lib/generators/ember/template_generator.rb, lib/generators/ember/view_generator.rb
Since thor@0.19.3, the warning message is shown for default type
mismatch.
ref: https://github.com/erikhuda/thor/commit/605897b5a02f10a4687237667cafa8dda6ae2016
We expect these options to be `nil` by default.
=> Remove type mismatched default value from generator options

README.md, ember-rails.gemspec
Since https://github.com/emberjs/ember-rails/pull/540, ember-rails supports Rails 4.2+.
Close https://github.com/emberjs/ember-rails/issues/542
=> Update supported Rails version

.travis.yml
https://www.ruby-lang.org/en/news/2017/03/28/ruby-2-2-7-released/
=> Test against Ruby 2.2.7

README.md
Throws this error when not using SSL: `redirection forbidden: http://emberjs.com/edge_template.rb -> https://emberjs.com/edge_template.rb (RuntimeError)`
=> Use SSL in template URL scheme

.travis.yml, ember-rails.gemspec, test/generators/install_generator_test.rb, test/hjstemplate_test.rb
I try to update Ruby versions on Travis CI.
However, as test errors occurred, I also addressed the following.
- Fix assert_match error of 'should unbind mustache templates' in HjsTemplateTest
- Modify VCR hook_info to faraday for InstallGeneratorTest of jruby test error
=> Update Ruby versions on Travis CI
